# -*- coding: utf-8 -*-
"""consistent Hashing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBlPtWWhSt5AgnYEa5X4yi0QF2mZnPv6
"""

import numpy as np

x = np.array([1, 2])
y = np.array([4, 6])

distance = np.sqrt(np.sum((x - y) ** 2))

dot_product = np.dot(x, y)
x_length = np.sqrt(np.sum(x ** 2))
y_length = np.sqrt(np.sum(y ** 2))

cosine = dot_product / (x_length * y_length)

print("Vector X =", x)
print("Vector Y =", y)
print("Euclidean Distance =", distance)
print("Cosine Similarity =", cosine)

import numpy as np

X = np.array([
    [2, 4, 6],
    [3, 9, 12],
    [5, 10, 15]
])

U = np.array([
    [1],
    [1],
    [0]
])

P = np.dot(X, U)

print("Original Matrix X:")
print(X)

print("\nProjection Vector U:")
print(U)

print("\nProjected Matrix P = XU:")
print(P)

import numpy as np

X = np.array([
    [2, 4, 6],
    [3, 9, 12]
])

U = np.array([
    [1],
    [1],
    [0]
])

P = np.dot(X, U)

d_before = np.sqrt(np.sum((X[0] - X[1]) ** 2))
d_after = np.sqrt(np.sum((P[0] - P[1]) ** 2))

print("Point 1 before projection:", X[0])
print("Point 2 before projection:", X[1])

print("\nPoint 1 after projection:", P[0])
print("Point 2 after projection:", P[1])

print("\nDistance before projection =", d_before)
print("Distance after projection =", d_after)

sets = {
    "S1": ["a", "b", "c"],
    "S2": ["b", "c", "d"],
    "S3": ["a", "c", "d"]
}

hash_functions = [
    {"a": 1, "b": 2, "c": 3, "d": 4},
    {"a": 3, "b": 1, "c": 4, "d": 2},
    {"a": 2, "b": 4, "c": 1, "d": 3}
]

signature = {}

for name in sets:
    values = []
    for h in hash_functions:
        min_value = min(h[item] for item in sets[name])
        values.append(min_value)
    signature[name] = values

print("Given Sets:")
for name in sets:
    print(name, "=", sets[name])

print("\nMinHash Signature Matrix:")
print("Hash\tS1\tS2\tS3")

for i in range(3):
    print("h" + str(i+1), "\t",
          signature["S1"][i], "\t",
          signature["S2"][i], "\t",
          signature["S3"][i])

import numpy as np

X = np.array([
    [2, 4],
    [3, 9],
    [5, 10],
    [6, 12]
])

mean = np.mean(X, axis=0)
X_centered = X - mean

cov_matrix = np.cov(X_centered.T)

eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

P = np.dot(X_centered, eigen_vectors)

print("Original Data:")
print(X)

print("\nMean:")
print(mean)

print("\nMean Centered Data:")
print(X_centered)

print("\nCovariance Matrix:")
print(cov_matrix)

print("\nEigen Values:")
print(eigen_values)

print("\nEigen Vectors:")
print(eigen_vectors)

print("\nProjected Data:")
print(P)