# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2KcTtpOFUgrSciVMHk1jU66DPOyf3JM
"""

import hashlib

class CountMinSketch:
    def __init__(self, l=3, b=10):
        self.l = l  # number of hash functions / rows
        self.b = b  # number of buckets / columns
        self.table = [[0 for _ in range(b)] for _ in range(l)]

    def hash_function(self, item, row):
        value = str(item) + str(row)
        hashed = hashlib.md5(value.encode()).hexdigest()
        return int(hashed, 16) % self.b

    def insert(self, item):
        for row in range(self.l):
            col = self.hash_function(item, row)
            self.table[row][col] += 1

    def estimate(self, item):
        values = []
        for row in range(self.l):
            col = self.hash_function(item, row)
            values.append(self.table[row][col])
        return min(values)

    def display(self):
        print("\nCount-Min Sketch Table:")
        for i in range(self.l):
            print(f"Hash {i+1}: {self.table[i]}")

cms = CountMinSketch(l=3, b=10)

stream = ["p1", "p2", "p1", "p3", "p1", "p2", "p4", "p1"]

for item in stream:
    cms.insert(item)

cms.display()

print("\nEstimated Frequencies:")
print("p1 =", cms.estimate("p1"))
print("p2 =", cms.estimate("p2"))
print("p3 =", cms.estimate("p3"))
print("p4 =", cms.estimate("p4"))