# -*- coding: utf-8 -*-
"""KdTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOtXMEQNjXjRC4cnCvfvyG2vywlDDI6e
"""

import math
class Node:
    def __init__(self, point):

        self.point = point
        self.left = None
        self.right = None
def build_tree(points, depth=0):
    if len(points) == 0:
       return None
    axis = depth % 2      # x then y then x...
    points.sort(key=lambda x: x[axis])
    mid = len(points)//2
    root = Node(points[mid])
    root.left = build_tree(points[:mid], depth+1)
    root.right = build_tree(points[mid+1:], depth+1)
    return root
def distance(p1,p2):
    x = (p1[0]-p2[0])**2
    y = (p1[1]-p2[1])**2
    return math.sqrt(x+y)
def nearest(root,target,depth=0,best=None):
    if root is None:
        return best
    d = distance(root.point,target)
    if best is None or d < best[1]:
        best = (root.point,d)
    axis = depth % 2
    if target[axis] < root.point[axis]:
        first = root.left
        second = root.right
    else:
        first = root.right
        second = root.left
    best = nearest(first,target,depth+1,best)
    if abs(target[axis]-root.point[axis]) < best[1]:
        best = nearest(second,target,depth+1,best)
    return best
points=[(7,2),(5,4),(9,6),(2,3),(4,7),(8,1)]
root = build_tree(points)
search_point = (6,7)
result = nearest(root,search_point)
print("Search Point :",search_point)
print("Nearest Point :",result[0])
print("Distance :",round(result[1],2))